# Generated by Django 5.0.6 on 2024-05-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ecostaff_images_alter_ecostaff_videos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecostaff',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.ecoimage'),
        ),
        migrations.AlterField(
            model_name='ecostaff',
            name='videos',
            field=models.ManyToManyField(blank=True, to='main.ecovideo'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
