# Generated by Django 5.0.6 on 2024-05-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ecostaff_images_alter_ecostaff_videos_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
