# Generated by Django 5.0.6 on 2024-05-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='media',
        ),
        migrations.RemoveField(
            model_name='order',
            name='master_classes',
        ),
        migrations.DeleteModel(
            name='MasterMedia',
        ),
        migrations.DeleteModel(
            name='MasterClass',
        ),
    ]
