# Generated by Django 5.0.6 on 2024-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_ecostaff_images_remove_ecostaff_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecostaff',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
