# Generated by Django 5.0.6 on 2024-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart_total_cost_alter_cart_items_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
