# Generated by Django 5.0.6 on 2024-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_message_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
