# Generated by Django 5.0.6 on 2024-06-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_message_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_name',
        ),
    ]
