# Generated by Django 5.0.6 on 2024-06-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_image_urls_ecostaff_images_ecostaff_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecostaff',
            name='upload',
        ),
        migrations.CreateModel(
            name='EcoStaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ecostaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecostaff_images', to='main.ecostaff')),
            ],
        ),
    ]
