# Generated by Django 5.0.6 on 2024-06-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_ecostaff_upload_ecostaffimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecostaff',
            name='images',
        ),
    ]
