# Generated by Django 5.0.6 on 2024-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_ecostaff_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecostaff',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='EcoStaffImage',
        ),
    ]
