# Generated by Django 5.0.6 on 2024-06-18 07:18

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ecostaff_image_urls_delete_ecostaffimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecostaff',
            name='image_urls',
        ),
        migrations.CreateModel(
            name='EcoStaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.upload_to)),
                ('ecostaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='main.ecostaff')),
            ],
        ),
        migrations.AddField(
            model_name='ecostaff',
            name='images',
            field=models.ManyToManyField(related_name='ecostaff_items', to='main.ecostaffimage'),
        ),
    ]
