# Generated by Django 5.0.6 on 2024-06-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_ecostaff_image_urls_ecostaffimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecostaff',
            name='images',
        ),
        migrations.AlterField(
            model_name='ecostaffimage',
            name='ecostaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.ecostaff'),
        ),
    ]
