# Generated by Django 5.0.6 on 2024-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_ecostaff_images_alter_ecostaffimage_ecostaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
