# Generated by Django 5.1.2 on 2024-10-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_message_user_name_alter_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPMessage',
        ),
    ]
