# Generated by Django 5.2.7 on 2025-10-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_vipmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
