# Generated by Django 5.2.7 on 2025-10-27 13:57

from django.db import migrations

def delete_activation_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        content_type = ContentType.objects.get(
            app_label='main',
            model='activation'
        )

        # Удаляем все permissions связанные с этой моделью
        Permission.objects.filter(
            content_type=content_type
        ).delete()

        print(f"Удалены permissions для модели activation")

    except ContentType.DoesNotExist:
        print("ContentType для модели activation не найден")

def recreate_activation_permissions(apps, schema_editor):
    """Функция для отката миграции"""
    from django.contrib.auth.management import create_permissions

    # Пересоздаем permissions для всех приложений
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0030_delete_activation_table'),
    ]

    operations = [
        migrations.RunPython(
            delete_activation_permissions,
            reverse_code=recreate_activation_permissions
        ),
    ]
